# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Stormcloak Games
email: hello@stormcloak.games
description: >- # this means to ignore newlines until "baseurl:"
  Developing fascinating and deep simulation video games
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stormcloak.games" # the base hostname & protocol for your site, e.g. http://example.com
patreon_username: jevon

twitter_username: stormcloakgames
patreon_username: jevon
facebook_username: adaptorygame
youtube_username: "@stormcloaknz"
tiktok_username: stormcloakgamesnz
instagram_username: stormcloakgames
bluesky_username: stormcloak.games
subreddit: adaptory

google_analytics: G-549M6W985W
mailing_list_url: https://dashboard.mailerlite.com/forms/797385/111659467457693483/share

disqus:
  shortname: stormcloak

mastodon:
  -
    username: stormcloak
    instance: mastodon.gamedev.place

truncate_words: 100

# Build settings
markdown: kramdown
theme: minima
minima:
  date_format: "%-d %B %Y"

plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-sitemap

permalink: /:categories/:year/:month/:day/:title

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - spec/
